<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wwonepagetemplate"
 *
 * Auto generated by Extension Builder 2019-08-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Onepage Template',
    'description' => 'This is a small demo one pager template. Take a look at the README for installation instructions.',
    'category' => 'templates',
    'author' => 'Wolfgang Wagner',
    'author_email' => 'wwagner@wwagner.net',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
