## https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SiteHandling/SiteSets.html
name: wwagner/wwonepagetemplate
label: Sitepackage for Onepage Template

## Load TypoScript, TSconfig and settings from dependencies
## bisherige Verbindungen des Templates alle löschen (auch das angelegte TYPO3 Template unter TypoScript > Root-Page
## Extensions sind zu installieren
dependencies:
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css
  - typo3/seo-sitemap